### ISSUE TITLE
Definitions that use polymorphism causes exception: Multiple entries with same key

### ISSUE THREAD

**Issue by rdiehl** [Swagger2Markup/swagger2markup#44] opened 2015-11-23 14:34 UTC
I originally logged this in swagger-core, and they advised me the issue was likely in swagger2markdown.  We have a number of models that use polymorphism, some of them extend multiple levels.  We're using Java annotations and the JAX-RS integration to create our Swagger definition at runtime.  I'm running into issues running our spec through the swagger2markup tool.  Here's our Java classes with the swagger annotations.

```java
@ApiModel(description = "The representation of a Chart-like object.", discriminator = "_class",
        subTypes = { TextChartDTO.class, ChartDTO.class, TableChartDTO.class })
public abstract class ChartableDTO implements Serializable {
    private String id;
    private String name;
    public String getId() { return id;}
    public void setId(final String id) {this.id = id;}
    public String getName() { return name;}
    public void setName(final String name) {this.name = name};
    // Various other properties
}

@ApiModel(description = "A parent class for all charts.", parent = ChartableDTO.class, discriminator = "_class",
        subTypes = { PieChartDTO.class, BarChartDTO.class, AreaChartDTO.class, LineChartDTO.class,
            MixedChartDTO.class, GaugeChartDTO.class })
public abstract class ChartDTO extends ChartableDTO implements Serializable {
    private ChartType chartType;
    public ChartType getChartType() {return chartType;}
    public void setChartType(final ChartType type) {this.chartType = type;}
    // various other properties
}

@ApiModel(description = "An area chart.", parent = ChartDTO.class)
public class AreaChartDTO extends ChartDTO implements Serializable {
    // various properties
}
```

When our swagger definition is generated, the definition for AreaChartDTO looks like this:
```json
"AreaChartDTO": {
"allOf": [
{
"$ref": "#/definitions/ChartDTO"
},
{
"type": "object",
"properties": {
  "id": {
    "type": "string"
  },
  "name": {
    "type": "string"
  },
},
.... more stuff
```

Note the existence of "allOf", referencing the ChartDTO definition, and then individual properties like "id" and "name".  The definition for ChartDTO looks like this:

```json
"ChartDTO": {
"allOf": [
{
"$ref": "#/definitions/ChartableDTO"
},
{
"type": "object",
"properties": {
  "id": {
    "type": "string"
  },
  "name": {
    "type": "string"
  },
.... more stuff
``` 

Again note that id and name are defined here.  The definition for ChartableDTO has them as well.  In effect what we're seeing is that properties from the base classes are being duplicated for each concrete class.  The full generated swagger is here: https://gist.github.com/rdiehl/6969b15f682387438662 

When the swagger definition goes through the swagger-parser, it parses successfully.  When I send the Swagger object that comes back from the parser into the Swagger2markup tool, it throws an exception about having multiple entries with the same key: "id".  

```
java.lang.IllegalArgumentException: Multiple entries with same key: id=io.swagger.models.properties.StringProperty@3729f557 and id=io.swagger.models.properties.StringProperty@3729f557
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.getAllProperties(DefinitionsDocument.java:232)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.getAllProperties(DefinitionsDocument.java:217)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.getAllProperties(DefinitionsDocument.java:226)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.propertiesSection(DefinitionsDocument.java:188)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.definition(DefinitionsDocument.java:184)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.definitions(DefinitionsDocument.java:134)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.build(DefinitionsDocument.java:111)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter.buildDocuments(Swagger2MarkupConverter.java:120)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter.intoFolder(Swagger2MarkupConverter.java:98)
	at com.docfinity.swagger.SwaggerDocGeneratorTests.convertRemoteSwaggerToAsciiDoc(SwaggerDocGeneratorTests.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

I briefly looked at the code, it seems like the use of ImmutableMap.Builder is inconsistent with how Swagger implements "allOf".

**Comment by RobWin** [comment] 2015-11-23 14:36
Hi,

thx for the great issue description. I have a look at it.
Its a duplicate of #39

**Comment by RobWin** [comment] 2015-11-23 14:48
My question is: Why do all definitions (ChartDTO, AreaChartDTO and ChartableDTO) need a `id` and `name` property, if it would be sufficient to have them in the `ChartableDTO` definition? It looks like a bug in the generator of the Swagger JSON, or?

**Comment by rdiehl** [comment] 2015-11-23 15:12
That was my original interpretation, yes.  It would seem to me that the use of "allOf" should inherit the common properties from the base class, and then only new properties would need to be included for each model.  I have logged this issue in swagger-core: https://github.com/swagger-api/swagger-core/issues/1549

Their first comment was to send me here, so I'm not sure whether it's an issue on their end or not.  We're using the annotations and JAX-RS integration to generate the API dynamically.

**Comment by RobWin** [comment] 2015-11-23 15:16
I can do a merge on my side, but it is still strange :)

**Comment by Kabhal** [comment] 2016-04-04 18:13
Properties are now merged in case of conflict.
Inheriting property takes precedence over parent property.
updated AsciiDocConverter::testSwagger2AsciiDocConversionWithPolymorphism for non-regression test.

**Closed by Kabhal** 2016-04-04 18:13 UTC
Labels: enhancement
