### ISSUE TITLE
Exception: Multiple entries with same key

### ISSUE THREAD

**Issue by msh321** [Swagger2Markup/swagger2markup#39] opened 2015-09-29 09:55 UTC
I have a Swagger Specification with a model where one definition includes another definition. In addition, the two definitions have a parameter by the same name.  If I run this Swagger Specification through Swagger2Markup, I get a `Multiple entries with same key` exception.

See this:
```
[BASH]# java -jar ./libs/swagger2markup-cli-0.0.1.jar generate -i ex.yaml -o s2m -l asciidoc
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from ex.yaml
Exception in thread "main" java.lang.IllegalArgumentException: Multiple entries with same key: propA=io.swagger.models.properties.StringProperty@1b4d89f and propA=io.swagger.models.properties.StringProperty@1b4d89f
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.getAllProperties(DefinitionsDocument.java:210)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.propertiesSection(DefinitionsDocument.java:172)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.definition(DefinitionsDocument.java:168)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.definitions(DefinitionsDocument.java:124)
	at io.github.robwin.swagger2markup.builder.document.DefinitionsDocument.build(DefinitionsDocument.java:107)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter.buildDocuments(Swagger2MarkupConverter.java:150)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter.intoFolder(Swagger2MarkupConverter.java:128)
	at me.ledin.swagger2markup.Application$Generate.run(Application.java:66)
	at me.ledin.swagger2markup.Application.main(Application.java:17)
```

I need to be able to declare the same property name in the two definitions; mostly because I need the documentation of the two properties to be a little bit different (small, yet important, difference).

The issue can be reproduced with the following example:

```yaml
swagger: '2.0'
info:
  description: TODO
  version: 0.0.1
  title: API Spec
  termsOfService: TODO
basePath: /v1
schemes:
  - http
paths:
  /aaa:
    post:
      tags:
        - AAA
      summary: TODO
      description: TODO
      operationId: aaa
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: TODO
          required: true
          schema:
            $ref: '#/definitions/AAA'
      responses:
        '200':
          description: Success
        '405':
          description: Invalid data
definitions:
  AAA:
    allOf:
      - $ref: '#/definitions/BBB'
      - type: object
        properties:
          propA:
            type: string
          propB:
            type: string
  BBB:
    type: object
    properties:
      propA:
        type: string
```

**Comment by RobWin** [comment] 2015-09-29 09:57
Hi thx. Do  you expect that `propA` of BBB overwrites `propA` of AAA ?

**Comment by msh321** [comment] 2015-09-29 10:10
Hello.

Well -- actually I expect the opposite; namely that `AAA.propA` overrides `BBB.propA`.  :smirk_cat:

**Comment by RobWin** [comment] 2015-09-29 13:08
What does the Swagger Spec v2 specify?

**Comment by msh321** [comment] 2015-09-30 11:18
Hmmm... I don't really understand what you mean with your question. Sorry.  :smiley:

**Comment by RobWin** [comment] 2015-09-30 11:30
I mean: Does the Swagger Spec v2 allow overwrites of properties? And which property has precedence?

**Comment by msh321** [comment] 2015-09-30 13:23
Aaahhh, understood.

Yes - overwriting properties is definitely allowed, as far as I understand. I would say that such a behavior would be covered by the term "polymorphism"...

**Comment by RobWin** [comment] 2015-09-30 14:22
Does your model work in http://editor.swagger.io ?

**Comment by msh321** [comment] 2015-09-30 19:54
Yes, the model works fine in the Swagger Editor.

Also, the Swagger Codegen is perfectly able to turn the model into code (for instance, Java and Perl client code).

**Comment by RobWin** [comment] 2015-11-09 15:10
I want to implement the feature now.
Could you please explain me, why `AAA.propA` should override `BBB.propA`.
If you need `AAA.propA` instead of `BBB.propA`, why do you use `allOf` at all?

**Comment by sg-ad** [comment] 2016-01-21 19:19
FYI, I've run into the same problem with a slight twist.  I thought I would add a quick description here in case it can help in the context of this enhancement.

We use Enunciate to generate the Swagger definition file.  I ran into a problem when our API referenced Jackson classes like `ArrayNode`, `ObjectNode` or `JsonNode`.  I asked for some details on what the Swagger Specification would expect [here](https://github.com/OAI/OpenAPI-Specification/issues/543), and how Enunciate interprets those types [here](https://github.com/stoicflame/enunciate/issues/256).

The main difference in this case is that properties don't get repeated, but the references get repeated.  It basically is the same problem, just slightly different incarnation.  

Thanks!

**Comment by RobWin** [comment] 2016-01-21 20:30
In your case, I think its a bug in enunciate.

**Comment by sg-ad** [comment] 2016-01-21 21:57
Indeed, in my case it will be addressed by Enunciate.  But my understanding is that it's technically not forbidden by JSON schema to have a `$ref` repeat at multiple levels in a hierarchy.  If feasible, I imagine it might be a good idea for Swagger2Markup to be tolerant of that scenario.

**Comment by RobWin** [comment] 2016-01-22 05:56
In my opinion, a $ref to the same type at multiple levels is a sign for a design error. You would not do that in Java as well.

**Comment by RobWin** [comment] 2016-02-12 16:30
Duplicate of #44

**Closed by RobWin** 2016-02-12 16:30 UTC
Labels: enhancement

**Comment by LUCKYZHOUSTAR** [comment] 2019-05-23 12:43
how to resolve this problem？
